#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6705135769                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.joonhwan.timewithme.time_with_me  # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Time with Me                              # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Share time with your precious people.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : JoonHwan
your_link                                 : https://github.com/teiresias22
your_city                                 : South Korea
email_address                             : teiresias1997@gmail.com  
facebook_username                         :                                           
instagram_username                        : j.oooon
twitter_username                          : 
github_username                           : teiresias22
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Share your calendar with others
    description                           : Create a calendar full of gorgeous images with people around you!
    fontawesome_icon_name                 : magic
    
  - title                                 : On Android and iPhone
    description                           : It is available for both Android and iPhone devices.
    fontawesome_icon_name                 : mobile

  - title                                 : Communicate together
    description                           : Let's communicate with each other by leaving hearts and comments on the schedule!
    fontawesome_icon_name                 : comment

  - title                                 : Record the location
    description                           : Record and share locations with images!
    fontawesome_icon_name                 : map

  - title                                 : Various D-day notations
    description                           : Through various D-Day recording methods, you can count the days that fit your schedule!
    fontawesome_icon_name                 : calendar-check
  
  - title                                 : Various categorization
    description                           : You can create various categories to record your schedules!
    fontawesome_icon_name                 : tag

  - title                                 : Different sorting methods
    description                           : You can find the item you want through various sorting methods!
    fontawesome_icon_name                 : clipboard-list

  - title                                 : Planned - New post notification
    description                           : We'll send you a notification when a new post is created on your calendar! This feature will be updated soon.
    fontawesome_icon_name                 : info-circle

  - title                                 : Planned - Add subscription
    description                           : If 3 or more people want to use it, you need to subscribe. This feature will be updated soon.
    fontawesome_icon_name                 : info-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#FF4875"
feature_icons_background_color            : "#FFF4CA"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"



####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
